### PR TITLE
Fix for the XCode 8 UIScreen.mainScreen issue

### PR DESCRIPTION
**Pull request by dpdragnev**
Based on the fix described in http://fluentreports.com/blog/?p=401

### CODE REVIEW

**Comment by NgSculptor** [comment]
+1

**Comment by Merott** [comment]
Apologies for leaving this for so long, been so busy. I will be updating the module in the next week or two. Thank you for the PR.

**Comment by dpdragnev** [comment]
My pleasure.  I figured that you must have been busy.

**Comment by Merott** [comment]
Thank you 👍

**Pull request merged**
